### PR TITLE
add first set of spanish translations of practicals

### PR DESCRIPTION
**Pull request by avallecam**

### CODE REVIEW

**Comment by TimTaylor** [comment]
@avallecam this is great! @thibautjombart can you take a look at this - you may want to make a few tweaks to the landing page before merging.

**Comment by thibautjombart** [comment]
Thanks for this! 
Page preview suggests everything works, see: 
https://deploy-preview-103--reconlearn.netlify.app/

We have not thought about translations much in the past, so there isn't a formal way to have a single post in different languages. This PR treats translations as new posts, which is fine, but as the most recent posts are displayed on the home page, it suggests the website content is in Spanish, which would confuse other users. 

Waiting for a better solution (probably months from now) could you make the follwing changes:

1. use the same dates for the new post as for the original ones, so new post don't end up on the landing page
2. add the names of the people involved in the translation to the list of original authors; translation does count as a contribution, and this was surely a lot of work!
3. I would suggest adding a tag 'Spanish' to the Yaml so that posts in Spanish can be found easily at https://www.reconlearn.org/topics.html

Happy to discuss the above if unclear or if you think of a better option

**Comment by avallecam** [comment]
Thanks for the feedback!

As you suggested, I've made the changes. Let me know if there are more update required!

The three post in Spanish are currently available [in this rute](https://deploy-preview-103--reconlearn.netlify.app/authors/jos%C3%A9-m.-velasco-espa%C3%B1a.html). It seems that in the preview version tag topics do not update quickly. In the local version them updates correctly.

Will be waiting for your comments!

**Comment by thibautjombart** [comment]
This looks very good, thanks! A minor point, you should also ideally add yourself as a Tag amongst authors in the Yaml header, so that you appear on the author list:
https://deploy-preview-103--reconlearn.netlify.app/authors.html

**Comment by avallecam** [comment]
Thanks! We are done with updates on this materials.

**Comment by thibautjombart** [comment]
Many thanks for this contribution - much appreciated!

**Pull request merged**
