### PR TITLE
Add Copenhagen practical

### PR DESCRIPTION
**Pull request by zkamvar**
**DO NOT MERGE THIS PR YET**

I'm in progress of adding the pieces of the practical incrementally. I will signal when all is good

### CODE REVIEW

**Comment by zkamvar** [comment]
The deploy preview is at https://deploy-preview-35--reconlearn-test.netlify.com/

**Comment by thibautjombart** [comment]
Thanks for this. Please address the following before merging:

- indentation of paragraphs is weird - see first section, either split paragraphs or merge them, but avoid carriage returns for each sentence

- screenshot1.png is missing

- screenshot2.png is missing

- maybe put the screenshot in a clearly named folder in `static`, other than `static/highres` which is meant for post pictures

- `boxplot(cph$age)` is a bit ugly; add legends, and maybe prettify a bit?; could be good to show alternatives: `hist()`; `plot(density(...)` or such, coz one boxplot only is a bit underwhelming (fine to keep it in though)

- `table(cph$case, cph$vomiting)` -> `table(case = cph$case, vomit = cph$vomiting)`; check other similar instances

**Comment by zkamvar** [comment]
> indentation of paragraphs is weird - see first section, either split paragraphs or merge them, but avoid carriage returns for each sentence

\*cringe\* ugh.... I forgot that github markdown variant actually respects carriage returns. I'll fix that.

> boxplot(cph$age) is a bit ugly; add legends, and maybe prettify a bit?

Agreed.

**Comment by zkamvar** [comment]
Also: I'm thinking of changing the panting that I have for the background image since it's by a Dutch painter when the outbreak was in a Denmark/

**Comment by zkamvar** [comment]
Ready for your approval. 

Note: The copenhagen case study has been split into four practicals... all of which are linked together

**Comment by zkamvar** [comment]
Okay... It's ready now

**Comment by thibautjombart** [comment]
Wikid, thanks!

**Pull request merged**
