### PR TITLE
New ebola practical

### PR DESCRIPTION
**Pull request by zkamvar**
This adds the adapted Ebola practical for the Colombia workshop by @zmcucunuba, @Imai-N, @annecori, and @finlaycampbell.

Things that still need to be done to ensure everything is cromulent:

 - [x] ensure that html widgets are properly presented ([narrator] they weren't)
 - [x] make sure header images are correct
 - [x] add note at the top of the practical informing users that this is an adaptation of an earlier practical. 
 - [x] change installation of outbreaker2 once it is on CRAN
 - [x] use github version of projections (see https://github.com/reconhub/projections/issues/11)
 - [x] change full_version to FALSE
 - [x] link to practicals

### CODE REVIEW

**Comment by zkamvar** [comment]
Note to @annecori, @finlaycampbell, @ImaiN, and @zmcucunuba, you can preview the site by clicking on the "Details" part of the checks for this PR (or just click here: https://deploy-preview-64--reconlearn.netlify.com/)

**Comment by Imai-N** [comment]
amazing thanks!
just a note to say that we want the `full_version = FALSE` version publicly available.

The `full_version = TRUE` also renders the answers and correct code snippets.
if you could put the FALSE version on RECONlearn for the delegates, then give us access to the TRUE version (so we have answers) that would be amazing.

**Comment by zkamvar** [comment]
> amazing thanks @zkamvar !!
> just a note to say that we want the `full_version = FALSE` version publicly available.
> 
> The `full_version = TRUE` also renders the answers and correct code snippets.
> if you could put the FALSE version on RECONlearn for the delegates, then give us access to the TRUE version (so we have answers) that would be amazing.

ISWICD!

**Comment by finlaycampbell** [comment]
It looks like `full_version = TRUE` in part 3?

**Comment by zkamvar** [comment]
> It looks like `full_version = TRUE` in part 3?

It was true for all of them, but I'm going to update them to parameterized reports so that the full versions aren't there.

**Comment by zkamvar** [comment]
I've created new figures like so:

```r
library("magick")

eb <- image_read(here::here("static/img/highres/ebola-strikes-back.jpg"))
plot(eb)
set.seed(53)
h <- function() sample(0:200, 1)
plot(image_modulate(eb, h()/1.5, 100, h()))
image_write(image_modulate(eb, h()/1.25, 20, h()), 
            path = here::here("static/img/highres/ebola-strikes-back-2.jpg"))
image_write(image_modulate(eb, h()/1.5, 100, h()),
            path = here::here("static/img/highres/ebola-strikes-back-2.jpg"))
```

**Comment by zkamvar** [comment]
I have been informed that this is satisfactory and am merging now.

**Pull request merged**
