### PR TITLE
add second set spanish translation of practicas

### PR DESCRIPTION
**Pull request by avallecam**
here we add:
- translated version of the practical real time response 2. [preview here](https://deploy-preview-104--reconlearn.netlify.app/post/real-time-response-2-spanish.html)
- new practical rmarkdown in spanish [preview here](https://deploy-preview-104--reconlearn.netlify.app/post/practical-rmarkdown-spanish.html)
- new practical about spatial analysis in spanish [preview here](https://deploy-preview-104--reconlearn.netlify.app/post/spatial-analysis-1-spanish.html)

all of them were updated following the suggestions shared in the previous PR

we may still need to update some parts of only one of these tutorials, so we'll report as soon as we are done!

also open to feedback!

### CODE REVIEW

**Comment by thibautjombart** [comment]
It looks absolutely great! One small caveat, if you could use older dates for two of these documents, that would be great, as for now they show up on the landing page - see below:
image

Ideally we should revamp the website with a 'language option' and these could be at the forefront in Spanish.. but I fear we lack time / resources for this at the moment. Sorry about that.

**Comment by avallecam** [comment]
thanks thibaut! we completely understand, problem solved!
we are still making last updates on one practical after this last commit. we let you know when we are done.

**Comment by thibautjombart** [comment]
Just checking: is this ready to merge now?

**Comment by avallecam** [comment]
not yet :) we're planning to make one more commit!

**Comment by thibautjombart** [comment]
Do poke me when this is ready to review - slack probably best. Meanwhile I'll keep ignoring the updates.

**Comment by avallecam** [comment]
done with commits, ready to review!

**Comment by thibautjombart** [comment]
Looks good to me. Thanks for all the hard work on these practicals!

**Pull request merged**
